---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-az1
  namespace: openstack
spec:
  env:
  - name: ANSIBLE_FORCE_COLOR
    value: 'True'
  networkAttachments:
  - ctlplane
  nodeTemplate:
    ansible:
      ansiblePort: 22
      ansibleUser: zuul
      ansibleVars:
        edpm_ceph_hci_pre_enabled_services:
        - ceph_mon
        - ceph_mgr
        - ceph_osd
        - ceph_rgw
        - ceph_nfs
        - ceph_rgw_frontend
        - ceph_nfs_frontend
        edpm_fips_mode: check
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_update: true
        edpm_network_config_os_net_config_mappings:
          edpm-compute-3:
            nic1: 52:54:00:60:00:59
            nic2: 52:54:00:35:09:a1
          edpm-compute-4:
            nic1: 52:54:00:e1:b1:6c
            nic2: 52:54:00:68:07:ba
          edpm-compute-5:
            nic1: 52:54:00:f6:df:4a
            nic2: 52:54:00:40:7d:23
        edpm_network_config_template: "---\n{% set mtu_list = [ctlplane_mtu] %}\n\
          {% for network in nodeset_networks %}\n{{ mtu_list.append(lookup('vars',\
          \ networks_lower[network] ~ '_mtu')) }}\n{%- endfor %}\n{% set min_viable_mtu\
          \ = mtu_list | max %}\nnetwork_config:\n- type: interface\n  name: nic1\n\
          \  use_dhcp: true\n  mtu: {{ min_viable_mtu }}\n- type: ovs_bridge\n  name:\
          \ {{ neutron_physical_bridge_name }}\n  mtu: {{ min_viable_mtu }}\n  use_dhcp:\
          \ false\n  dns_servers: {{ ctlplane_dns_nameservers }}\n  domain: {{ dns_search_domains\
          \ }}\n  addresses:\n  - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}\n\
          \  routes: {{ ctlplane_host_routes }}\n  members:\n  - type: interface\n\
          \    name: nic2\n    mtu: {{ min_viable_mtu }}\n    # force the MAC address\
          \ of the bridge to this interface\n    primary: true\n{% for network in\
          \ nodeset_networks %}\n  - type: vlan\n    mtu: {{ lookup('vars', networks_lower[network]\
          \ ~ '_mtu') }}\n    vlan_id: {{ lookup('vars', networks_lower[network] ~\
          \ '_vlan_id') }}\n    addresses:\n    - ip_netmask:\n        {{ lookup('vars',\
          \ networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network]\
          \ ~ '_cidr') }}\n    routes: {{ lookup('vars', networks_lower[network] ~\
          \ '_host_routes') }}\n{% endfor %}\n"
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false
        edpm_selinux_mode: enforcing
        edpm_sshd_allowed_ranges:
        - 192.168.133.0/24
        - 192.168.122.0/24
        - 192.168.111.0/24
        edpm_sshd_configure_firewall: true
        enable_debug: true
        gather_facts: false
        neutron_physical_bridge_name: br-ex
        edpm_ovn_bridge_mappings: ["leaf1:br-ex"]
        edpm_enable_chassis_gw: true
        edpm_ovn_availability_zones:
          - az1
        neutron_public_interface_name: eth0
        service_net_map:
          nova_api_network: internalapi
          nova_libvirt_network: internalapi
        storage_mgmt_cidr: '24'
        storage_mgmt_host_routes: []
        storage_mgmt_mtu: 9000
        storage_mgmt_vlan_id: 33
        storage_mtu: 9000
        timesync_ntp_servers:
        - hostname: pool.ntp.org
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    extraMounts:
    - extraVolType: Ceph
      mounts:
      - mountPath: /etc/ceph
        name: ceph
        readOnly: true
      volumes:
      - name: ceph
        secret:
          secretName: ceph-conf-files
    managementNetwork: ctlplane
    networks:
    - defaultRoute: true
      name: ctlplane
      subnetName: subnet2
    - name: internalapi
      subnetName: subnet2
    - name: storage
      subnetName: subnet2
    - name: tenant
      subnetName: subnet2
  nodes:
    edpm-compute-3:
      ansible:
        host: 192.168.133.180
      hostName: compute-3
      networks:
      - defaultRoute: true
        fixedIP: 192.168.133.180
        name: ctlplane
        subnetName: subnet2
      - name: internalapi
        subnetName: subnet2
      - name: storage
        subnetName: subnet2
      - name: storagemgmt
        subnetName: subnet2
      - name: tenant
        subnetName: subnet2
    edpm-compute-4:
      ansible:
        host: 192.168.133.109
      hostName: compute-4
      networks:
      - defaultRoute: true
        fixedIP: 192.168.133.109
        name: ctlplane
        subnetName: subnet2
      - name: internalapi
        subnetName: subnet2
      - name: storage
        subnetName: subnet2
      - name: storagemgmt
        subnetName: subnet2
      - name: tenant
        subnetName: subnet2
    edpm-compute-5:
      ansible:
        host: 192.168.133.185
      hostName: compute-5
      networks:
      - defaultRoute: true
        fixedIP: 192.168.133.185
        name: ctlplane
        subnetName: subnet2
      - name: internalapi
        subnetName: subnet2
      - name: storage
        subnetName: subnet2
      - name: storagemgmt
        subnetName: subnet2
      - name: tenant
        subnetName: subnet2
  preProvisioned: true
  services:
  - install-certs
  - ceph-client
  - ovn
  - neutron-metadata
  - libvirt
  - nova-custom-ceph-az1
